name: build_workflow
on : push
jobs:
    build_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: install dependencies
              run: npm install
            - name: lint
              run: npm run lint
            - name: test
              run: npm run test
            - name: build
              run: npm run build
    deploy_job:
        runs-on: ubuntu-latest
        needs: build_job
        steps:
            - name: Deploy
              run: echo "Deploying application..."