name: event_workflow
on:
  issues:
    types: [opened, edited, closed]
jobs:
  event_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Log issue event
        run: |
          echo "Issue event triggered {{githhub.event.action}}"
          echo "Issue titlte: ${{ github.event.issue.title }}"
          echo "Issue body: ${{ github.event.issue.body }}"
          echo "Issue number: ${{ github.event.issue.number }}"
      - name: Notify on issue event
        run: echo "Notification sent for issue event"